version: "2.1"
services:
  springbootaxonkafka:
    build:
      context: ../../
    image: springbootaxonkafka:latest
    container_name: springbootaxonkafka
    ports:
      - "9998:9998"
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test