spring:
  profiles:
    active: local
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    show_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

auth:
  userinfoUrl: https://auth-qa.cpfb.gds-gov.tech/auth/realms/CDS-LOCAL/protocol/openid-connect/userinfo
  clientid: portus
  bypass: 'false'

axon:
  serializer:
    events: jackson
  kafka:
    bootstrap-servers: localhost:9092
    client-id: kafka-local.001
    default-topic: local.event
    properties:
      security.protocol: PLAINTEXT
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: product
      retries: 3
      event-processor-mode: subscribing
    fetcher:
      poll-timeout: 3000
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
  axonserver:
    enabled: false

server:
  port: 9998
---