spring:
  profiles:
    active: local
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

auth:
  userinfoUrl: https://auth-qa.cpfb.gds-gov.tech/auth/realms/CDS-LOCAL/protocol/openid-connect/userinfo
  clientid: portus
  bypass: 'false'

axon:
  serializer:
    events: jackson
  kafka:
    bootstrap-servers: localhost:9092
    client-id: kafka-local.001
    default-topic: local.event
    properties:
      security.protocol: PLAINTEXT
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: product
      retries: 3
      event-processor-mode: subscribing
    fetcher:
      poll-timeout: 3000
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
  axonserver:
    enabled: false

server:
  port: 9998
---